package webapp.entity;
// default package
// Generated Aug 7, 2017 9:40:29 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DataTravel generated by hbm2java
 */
@Entity
@Table(name = "data_travel", catalog = "travelrecord")
public class DataTravel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer datatravelNo;
	private Date dateTravel;
	private String start;
	private String end;
	private String conveyance;
	private String codeConveyance;
	private Integer distance;
	private Integer expenses;
	private String orther;
	private Integer charges;
	private String bill;
	private String reason;
	private String travelwith;
	private int userId;

	public DataTravel() {
	}

	public DataTravel(Date dateTravel, String start, String end, String conveyance, String reason, int userId) {
		this.dateTravel = dateTravel;
		this.start = start;
		this.end = end;
		this.conveyance = conveyance;
		this.reason = reason;
		this.userId = userId;
	}

	public DataTravel(Date dateTravel, String start, String end, String conveyance, String codeConveyance,
			Integer distance, Integer expenses, String orther, Integer charges, String bill, String reason,
			String travelwith, int userId) {
		this.dateTravel = dateTravel;
		this.start = start;
		this.end = end;
		this.conveyance = conveyance;
		this.codeConveyance = codeConveyance;
		this.distance = distance;
		this.expenses = expenses;
		this.orther = orther;
		this.charges = charges;
		this.bill = bill;
		this.reason = reason;
		this.travelwith = travelwith;
		this.userId = userId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "datatravel_no", unique = true, nullable = false)
	public Integer getDatatravelNo() {
		return this.datatravelNo;
	}

	public void setDatatravelNo(Integer datatravelNo) {
		this.datatravelNo = datatravelNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_travel", nullable = false, length = 10)
	public Date getDateTravel() {
		return this.dateTravel;
	}

	public void setDateTravel(Date dateTravel) {
		this.dateTravel = dateTravel;
	}

	@Column(name = "start", nullable = false, length = 45)
	public String getStart() {
		return this.start;
	}

	public void setStart(String start) {
		this.start = start;
	}

	@Column(name = "end", nullable = false, length = 45)
	public String getEnd() {
		return this.end;
	}

	public void setEnd(String end) {
		this.end = end;
	}

	@Column(name = "conveyance", nullable = false, length = 20)
	public String getConveyance() {
		return this.conveyance;
	}

	public void setConveyance(String conveyance) {
		this.conveyance = conveyance;
	}

	@Column(name = "code_conveyance", length = 10)
	public String getCodeConveyance() {
		return this.codeConveyance;
	}

	public void setCodeConveyance(String codeConveyance) {
		this.codeConveyance = codeConveyance;
	}

	@Column(name = "distance")
	public Integer getDistance() {
		return this.distance;
	}

	public void setDistance(Integer distance) {
		this.distance = distance;
	}

	@Column(name = "expenses")
	public Integer getExpenses() {
		return this.expenses;
	}

	public void setExpenses(Integer expenses) {
		this.expenses = expenses;
	}

	@Column(name = "orther", length = 20)
	public String getOrther() {
		return this.orther;
	}

	public void setOrther(String orther) {
		this.orther = orther;
	}

	@Column(name = "charges")
	public Integer getCharges() {
		return this.charges;
	}

	public void setCharges(Integer charges) {
		this.charges = charges;
	}

	@Column(name = "bill", length = 45)
	public String getBill() {
		return this.bill;
	}

	public void setBill(String bill) {
		this.bill = bill;
	}

	@Column(name = "reason", nullable = false, length = 20)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "travelwith", length = 45)
	public String getTravelwith() {
		return this.travelwith;
	}

	public void setTravelwith(String travelwith) {
		this.travelwith = travelwith;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

}
