package webapp.entity;
// default package
// Generated Aug 7, 2017 9:40:29 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ForAdmin generated by hbm2java
 */
@Entity
@Table(name = "for_admin", catalog = "travelrecord")
public class ForAdmin implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int userId;
	private int rateCar;
	private int rateMotorcycle;
	private Date scheduled;

	public ForAdmin() {
	}

	public ForAdmin(int userId, int rateCar, int rateMotorcycle, Date scheduled) {
		this.userId = userId;
		this.rateCar = rateCar;
		this.rateMotorcycle = rateMotorcycle;
		this.scheduled = scheduled;
	}

	@Id

	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "rate_car", nullable = false)
	public int getRateCar() {
		return this.rateCar;
	}

	public void setRateCar(int rateCar) {
		this.rateCar = rateCar;
	}

	@Column(name = "rate_motorcycle", nullable = false)
	public int getRateMotorcycle() {
		return this.rateMotorcycle;
	}

	public void setRateMotorcycle(int rateMotorcycle) {
		this.rateMotorcycle = rateMotorcycle;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "scheduled", nullable = false, length = 10)
	public Date getScheduled() {
		return this.scheduled;
	}

	public void setScheduled(Date scheduled) {
		this.scheduled = scheduled;
	}

}
