package webapp.entity;
// default package
// Generated Aug 21, 2017 4:03:54 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "location", catalog = "travelrecord")
public class Location implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 55674450778366808L;
	private String nameLocation;
	private String addressLocation;
	private String locationLat;
	private String locationLng;

	public Location() {
	}

	public Location(String nameLocation, String addressLocation, String locationLat, String locationLng) {
		this.nameLocation = nameLocation;
		this.addressLocation = addressLocation;
		this.locationLat = locationLat;
		this.locationLng = locationLng;
	}

	@Id

	@Column(name = "name_location", unique = true, nullable = false, length = 50)
	public String getNameLocation() {
		return this.nameLocation;
	}

	public void setNameLocation(String nameLocation) {
		this.nameLocation = nameLocation;
	}

	@Column(name = "address_location", nullable = false, length = 100)
	public String getAddressLocation() {
		return this.addressLocation;
	}

	public void setAddressLocation(String addressLocation) {
		this.addressLocation = addressLocation;
	}

	@Column(name = "location_lat", nullable = false, length = 45)
	public String getLocationLat() {
		return this.locationLat;
	}

	public void setLocationLat(String locationLat) {
		this.locationLat = locationLat;
	}

	@Column(name = "location_lng", nullable = false, length = 45)
	public String getLocationLng() {
		return this.locationLng;
	}

	public void setLocationLng(String locationLng) {
		this.locationLng = locationLng;
	}

}
